config/routes.rb
ClosingChecklist::Application.routes.draw do
  resources :items

  resources :phases

  resources :deals

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  attr_accessible :name, :phases_attributes
  has_many :phases
  accepts_nested_attributes_for :phases, allow_destroy: true
  validates :name, presence: true, uniqueness: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :done, :due, :name, :notes, :owner_id, :party_id, :phase_id
  belongs_to :phase
  validates :name, presence: true
end

app/models/phase.rb
class Phase < ActiveRecord::Base
  attr_accessible :deal_id, :name, :position, :items_attributes
  belongs_to :deal
  has_many :items
  accepts_nested_attributes_for :items, allow_destroy: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deals }
    end
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
    @deal = Deal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/new
  # GET /deals/new.json
  def new
    @deal = Deal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/1/edit
  def edit
    @deal = Deal.find(params[:id])
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(params[:deal])

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render json: @deal, status: :created, location: @deal }
      else
        format.html { render action: "new" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /deals/1
  # PUT /deals/1.json
  def update
    @deal = Deal.find(params[:id])

    respond_to do |format|
      if @deal.update_attributes(params[:deal])
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to deals_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # GET /items
  # GET /items.json
  def index
    @items = Item.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @items }
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/new
  # GET /items/new.json
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params[:item])

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render json: @item, status: :created, location: @item }
      else
        format.html { render action: "new" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.json
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/phases_controller.rb
class PhasesController < ApplicationController
  # GET /phases
  # GET /phases.json
  def index
    @phases = Phase.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @phases }
    end
  end

  # GET /phases/1
  # GET /phases/1.json
  def show
    @phase = Phase.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @phase }
    end
  end

  # GET /phases/new
  # GET /phases/new.json
  def new
    @phase = Phase.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @phase }
    end
  end

  # GET /phases/1/edit
  def edit
    @phase = Phase.find(params[:id])
  end

  # POST /phases
  # POST /phases.json
  def create
    @phase = Phase.new(params[:phase])

    respond_to do |format|
      if @phase.save
        format.html { redirect_to @phase, notice: 'Phase was successfully created.' }
        format.json { render json: @phase, status: :created, location: @phase }
      else
        format.html { render action: "new" }
        format.json { render json: @phase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /phases/1
  # PUT /phases/1.json
  def update
    @phase = Phase.find(params[:id])

    respond_to do |format|
      if @phase.update_attributes(params[:phase])
        format.html { redirect_to @phase, notice: 'Phase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @phase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phases/1
  # DELETE /phases/1.json
  def destroy
    @phase = Phase.find(params[:id])
    @phase.destroy

    respond_to do |format|
      format.html { redirect_to phases_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/phases_helper.rb
module PhasesHelper
end

app/views/deals/_form.html.erb
<%= nested_form_for(@deal) do |f| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% @deal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  

	<%= f.fields_for :phases %>
	
	<p>
		<%=f.link_to_add "Add a phase", :phases %>
	</p>
	
	<div class="actions">
    <%= f.submit %>
  </div>
	
<% end %>

app/views/deals/_item_fields.html.erb
<%= f.label :name, "Item:" %>
<%= f.text_field :name %>
<%= f.link_to_remove "Remove this item"%>

app/views/deals/_phase_fields.html.erb
<%= f.label :name, "Phase:" %>
<%= f.text_field :name %>
<%= f.link_to_remove "Remove this phase"%>
<%= f.fields_for :items %>
<p>
	<%=f.link_to_add "Add an item", :items %>
</p>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<h1>Listing deals</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @deals.each do |deal| %>
  <tr>
    <td><%= deal.name %></td>
    <td><%= link_to 'Show', deal %></td>
    <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
    <td><%= link_to 'Destroy', deal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Deal', new_deal_path %>

app/views/deals/new.html.erb
<h1>New deal</h1>

<%= render 'form' %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>
  	<%= best_in_place @deal, :name %>
	</b>
</p>

<ul>
<% @deal.phases.each do | p | %>
	<li>
		<%= best_in_place p, :name %>
		<ul>
			<% p.items.each do |i| %>
				<li>
					<%= best_in_place i, :name %>
				</li>
			<% end %>
		</ul>
	</li>
<% end %>
</ul>

<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :phase_id %><br />
    <%= f.number_field :phase_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :due %><br />
    <%= f.date_select :due %>
  </div>
  <div class="field">
    <%= f.label :done %><br />
    <%= f.check_box :done %>
  </div>
  <div class="field">
    <%= f.label :owner_id %><br />
    <%= f.number_field :owner_id %>
  </div>
  <div class="field">
    <%= f.label :party_id %><br />
    <%= f.number_field :party_id %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h1>Listing items</h1>

<table>
  <tr>
    <th>Phase</th>
    <th>Name</th>
    <th>Due</th>
    <th>Done</th>
    <th>Owner</th>
    <th>Party</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @items.each do |item| %>
  <tr>
    <td><%= item.phase_id %></td>
    <td><%= item.name %></td>
    <td><%= item.due %></td>
    <td><%= item.done %></td>
    <td><%= item.owner_id %></td>
    <td><%= item.party_id %></td>
    <td><%= item.notes %></td>
    <td><%= link_to 'Show', item %></td>
    <td><%= link_to 'Edit', edit_item_path(item) %></td>
    <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Phase:</b>
  <%= @item.phase_id %>
</p>

<p>
  <b>Name:</b>
  <%= @item.name %>
</p>

<p>
  <b>Due:</b>
  <%= @item.due %>
</p>

<p>
  <b>Done:</b>
  <%= @item.done %>
</p>

<p>
  <b>Owner:</b>
  <%= @item.owner_id %>
</p>

<p>
  <b>Party:</b>
  <%= @item.party_id %>
</p>

<p>
  <b>Notes:</b>
  <%= @item.notes %>
</p>


<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClosingChecklist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/phases/_form.html.erb
<%= form_for(@phase) do |f| %>
  <% if @phase.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phase.errors.count, "error") %> prohibited this phase from being saved:</h2>

      <ul>
      <% @phase.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :deal_id %><br />
    <%= f.number_field :deal_id %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phases/edit.html.erb
<h1>Editing phase</h1>

<%= render 'form' %>

<%= link_to 'Show', @phase %> |
<%= link_to 'Back', phases_path %>

app/views/phases/index.html.erb
<h1>Listing phases</h1>

<table>
  <tr>
    <th>Deal</th>
    <th>Position</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @phases.each do |phase| %>
  <tr>
    <td><%= phase.deal_id %></td>
    <td><%= phase.position %></td>
    <td><%= phase.name %></td>
    <td><%= link_to 'Show', phase %></td>
    <td><%= link_to 'Edit', edit_phase_path(phase) %></td>
    <td><%= link_to 'Destroy', phase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Phase', new_phase_path %>

app/views/phases/new.html.erb
<h1>New phase</h1>

<%= render 'form' %>

<%= link_to 'Back', phases_path %>

app/views/phases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Deal:</b>
  <%= @phase.deal_id %>
</p>

<p>
  <b>Position:</b>
  <%= @phase.position %>
</p>

<p>
  <b>Name:</b>
  <%= @phase.name %>
</p>


<%= link_to 'Edit', edit_phase_path(@phase) %> |
<%= link_to 'Back', phases_path %>